import pool from './pool.js';

export const VERIFIED_QUESTION_BANK = [
  // POLITY QUESTIONS (1-20)
  {
    id: 'q_polity_01',
    subjectId: 'sub_polity',
    topicId: 'top_rights',
    conceptId: 'c_art32',
    type: 'MCQ' as const,
    question: 'Which of the following Writs can be issued by the Supreme Court under Article 32 against both judicial and quasi-judicial authorities to quash an order already passed?',
    question_en: 'Which of the following Writs can be issued by the Supreme Court under Article 32 against both judicial and quasi-judicial authorities to quash an order already passed?',
    question_hi: 'अनुच्छेद 32 के तहत सर्वोच्च न्यायालय द्वारा न्यायिक और अर्द्ध-न्यायिक दोनों प्राधिकरणों के खिलाफ पहले से पारित आदेश को रद्द करने के लिए निम्नलिखित में से कौन सी रिट जारी की जा सकती है?',
    options: [
      { id: '0', text: 'Mandamus' },
      { id: '1', text: 'Prohibition' },
      { id: '2', text: 'Certiorari' },
      { id: '3', text: 'Quo-Warranto' },
    ],
    options_en: [
      { id: '0', text: 'Mandamus' },
      { id: '1', text: 'Prohibition' },
      { id: '2', text: 'Certiorari' },
      { id: '3', text: 'Quo-Warranto' },
    ],
    options_hi: [
      { id: '0', text: 'परमादेश (Mandamus)' },
      { id: '1', text: 'प्रतिषेध (Prohibition)' },
      { id: '2', text: 'उत्प्रेषण (Certiorari)' },
      { id: '3', text: 'अधिकार-पृच्छा (Quo-Warranto)' },
    ],
    correctAnswer: '2',
    explanation: 'Certiorari is corrective in nature and is issued to quash the order already passed by an inferior court or quasi-judicial body lacking jurisdiction or in violation of natural justice.',
    explanation_en: 'Certiorari is corrective in nature and is issued to quash the order already passed by an inferior court or quasi-judicial body lacking jurisdiction or in violation of natural justice.',
    explanation_hi: 'उत्प्रेषण रिट उपचारात्मक प्रकृति की होती है और यह किसी निचली अदालत या अर्द्ध-न्यायिक निकाय द्वारा अधिकार क्षेत्र के अभाव या प्राकृतिक न्याय के उल्लंघन में पहले से पारित आदेश को रद्द करने के लिए जारी की जाती है।',
    difficulty: 'MEDIUM' as const,
    examTag: 'UPSC CSE Prelims PYQ',
    pyqYear: 2022,
    isPyq: true,
    source: 'UPSC Civil Services Examination 2022',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_polity_02',
    subjectId: 'sub_polity',
    topicId: 'top_rights',
    conceptId: 'c_art21',
    type: 'MCQ' as const,
    question: 'A legislation which confers on the executive or administrative authority an unguided and uncontrolled discretionary power in the matter of application of law violates which of the following Articles of the Constitution of India?',
    question_en: 'A legislation which confers on the executive or administrative authority an unguided and uncontrolled discretionary power in the matter of application of law violates which of the following Articles of the Constitution of India?',
    question_hi: 'कोई कानून जो कानून के अनुप्रयोग के मामले में कार्यपालिका या प्रशासनिक प्राधिकरण को एक अनियंत्रित और विवेकाधीन शक्ति प्रदान करता है, भारत के संविधान के निम्नलिखित में से किस अनुच्छेद का उल्लंघन करता है?',
    options: [
      { id: '0', text: 'Article 14' },
      { id: '1', text: 'Article 28' },
      { id: '2', text: 'Article 32' },
      { id: '3', text: 'Article 44' },
    ],
    options_en: [
      { id: '0', text: 'Article 14' },
      { id: '1', text: 'Article 28' },
      { id: '2', text: 'Article 32' },
      { id: '3', text: 'Article 44' },
    ],
    options_hi: [
      { id: '0', text: 'अनुच्छेद 14' },
      { id: '1', text: 'अनुच्छेद 28' },
      { id: '2', text: 'अनुच्छेद 32' },
      { id: '3', text: 'अनुच्छेद 44' },
    ],
    correctAnswer: '0',
    explanation: 'Unguided, arbitrary, or uncontrolled discretionary power given to the executive violates Article 14 (Right to Equality and Non-Arbitrariness), as held in EP Royappa and Maneka Gandhi rulings.',
    explanation_en: 'Unguided, arbitrary, or uncontrolled discretionary power given to the executive violates Article 14 (Right to Equality and Non-Arbitrariness), as held in EP Royappa and Maneka Gandhi rulings.',
    explanation_hi: 'कार्यपालिका को दी गई अनियंत्रित या मनमानी विवेकाधीन शक्ति अनुच्छेद 14 (समानता और गैर-मनमानेपन का अधिकार) का उल्लंघन करती है।',
    difficulty: 'HARD' as const,
    examTag: 'UPSC CSE Prelims 2021 PYQ',
    pyqYear: 2021,
    isPyq: true,
    source: 'UPSC CSE 2021 Prelims Paper-1',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_polity_03',
    subjectId: 'sub_polity',
    topicId: 'top_const',
    conceptId: 'c_art21',
    type: 'MCQ' as const,
    question: 'Which one of the following statements best reflects the Chief purpose of the "Constitution" of a country?',
    question_en: 'Which one of the following statements best reflects the Chief purpose of the "Constitution" of a country?',
    question_hi: 'निम्नलिखित में से कौन सा कथन किसी देश के "संविधान" के मुख्य उद्देश्य को सर्वोत्तम रूप से दर्शाता है?',
    options: [
      { id: '0', text: 'It determines the objective for making necessary laws.' },
      { id: '1', text: 'It enables the creation of political offices and a government.' },
      { id: '2', text: 'It defines and limits the powers of the government.' },
      { id: '3', text: 'It secures social justice, social equality and social security.' },
    ],
    options_en: [
      { id: '0', text: 'It determines the objective for making necessary laws.' },
      { id: '1', text: 'It enables the creation of political offices and a government.' },
      { id: '2', text: 'It defines and limits the powers of the government.' },
      { id: '3', text: 'It secures social justice, social equality and social security.' },
    ],
    options_hi: [
      { id: '0', text: 'यह आवश्यक कानून बनाने के उद्देश्य को निर्धारित करता है।' },
      { id: '1', text: 'यह राजनीतिक पदों और सरकार के गठन को सक्षम बनाता है।' },
      { id: '2', text: 'यह सरकार की शक्तियों को परिभाषित और सीमित करता है (संवैधानिकता)।' },
      { id: '3', text: 'यह सामाजिक न्याय, सामाजिक समानता और सामाजिक सुरक्षा सुनिश्चित करता है।' },
    ],
    correctAnswer: '2',
    explanation: 'The fundamental purpose of constitutionalism is constitutional limitation — defining and limiting the powers of government to protect liberty.',
    explanation_en: 'The fundamental purpose of constitutionalism is constitutional limitation — defining and limiting the powers of government to protect liberty.',
    explanation_hi: 'संविधानवाद का मुख्य उद्देश्य सरकार की शक्तियों को परिभाषित और सीमित करना है ताकि नागरिकों की स्वतंत्रता की रक्षा हो सके।',
    difficulty: 'MEDIUM' as const,
    examTag: 'UPSC CSE Prelims 2023 PYQ',
    pyqYear: 2023,
    isPyq: true,
    source: 'UPSC CSE 2023 Prelims Paper-1',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_polity_04',
    subjectId: 'sub_polity',
    topicId: 'top_judiciary',
    conceptId: 'c_art226',
    type: 'MCQ' as const,
    question: 'With reference to the High Courts in India, consider the following statements:\n1. A High Court in India can issue writs to any person, authority or government beyond its territorial jurisdiction if the cause of action arises within its territory.\n2. The writ jurisdiction of the High Court under Article 226 is wider than that of the Supreme Court under Article 32.',
    options: [
      { id: '0', text: '1 only' },
      { id: '1', text: '2 only' },
      { id: '2', text: 'Both 1 and 2' },
      { id: '3', text: 'Neither 1 nor 2' },
    ],
    correctAnswer: '2',
    explanation: 'Both statements are correct. Clause (2) of Article 226 allows High Courts extra-territorial writ power if cause of action wholly or in part arises within its territory. High Court writ jurisdiction also extends to ordinary legal rights, making it wider than Article 32.',
    difficulty: 'HARD' as const,
    examTag: 'UPSC CSE Prelims 2020 PYQ',
    pyqYear: 2020,
    isPyq: true,
    source: 'UPSC CSE 2020 Prelims',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_polity_05',
    subjectId: 'sub_polity',
    topicId: 'top_federalism',
    conceptId: 'c_fiscal_fed',
    type: 'MCQ' as const,
    question: 'Which of the following bodies is constitutional in nature?\n1. Goods and Services Tax (GST) Council\n2. NITI Aayog\n3. National Development Council\n4. Finance Commission',
    options: [
      { id: '0', text: '1 and 4 only' },
      { id: '1', text: '1, 2 and 4 only' },
      { id: '2', text: '4 only' },
      { id: '3', text: '1, 3 and 4 only' },
    ],
    correctAnswer: '0',
    explanation: 'GST Council (Article 279A) and Finance Commission (Article 280) are constitutional bodies. NITI Aayog and NDC are extra-constitutional/executive bodies.',
    difficulty: 'EASY' as const,
    examTag: 'UPSC CSE Prelims PYQ',
    pyqYear: 2021,
    isPyq: true,
    source: 'UPSC CSE Prelims',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },

  // ECONOMY QUESTIONS (21-40)
  {
    id: 'q_econ_01',
    subjectId: 'sub_economy',
    topicId: 'top_monetary',
    conceptId: 'c_mpc',
    type: 'MCQ' as const,
    question: 'If the RBI decides to adopt an expansionary monetary policy, which of the following would it NOT do?\n1. Cut and optimize the Statutory Liquidity Ratio (SLR)\n2. Increase the Marginal Standing Facility (MSF) Rate\n3. Cut the Bank Rate and Repo Rate',
    options: [
      { id: '0', text: '1 and 2 only' },
      { id: '1', text: '2 only' },
      { id: '2', text: '1 and 3 only' },
      { id: '3', text: '1, 2 and 3' },
    ],
    correctAnswer: '1',
    explanation: 'In an expansionary monetary policy, the RBI wants to increase money supply and reduce lending rates. Increasing the MSF rate makes borrowing costlier (contractionary), so RBI will NOT increase MSF.',
    difficulty: 'MEDIUM' as const,
    examTag: 'UPSC CSE Prelims 2020 PYQ',
    pyqYear: 2020,
    isPyq: true,
    source: 'UPSC CSE 2020 Prelims Paper-1',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_econ_02',
    subjectId: 'sub_economy',
    topicId: 'top_monetary',
    conceptId: 'c_mpc',
    type: 'MCQ' as const,
    question: 'With reference to the Indian economy, demand-pull inflation can be caused/increased by which of the following?\n1. Expansionary policies\n2. Fiscal stimulus\n3. Inflation-indexing wages\n4. Higher purchasing power\n5. Rising interest rates',
    options: [
      { id: '0', text: '1, 2 and 4 only' },
      { id: '1', text: '1, 2, 3 and 4 only' },
      { id: '2', text: '3 and 5 only' },
      { id: '3', text: '1, 2, 3, 4 and 5' },
    ],
    correctAnswer: '1',
    explanation: 'Rising interest rates curb borrowing and cool down aggregate demand, reducing demand-pull inflation. 1, 2, 3, and 4 all expand purchasing power and aggregate demand, driving demand-pull inflation.',
    difficulty: 'HARD' as const,
    examTag: 'UPSC CSE Prelims 2021 PYQ',
    pyqYear: 2021,
    isPyq: true,
    source: 'UPSC CSE 2021 Prelims Paper-1',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_econ_03',
    subjectId: 'sub_economy',
    topicId: 'top_fiscal',
    conceptId: 'c_fin_comm',
    type: 'MCQ' as const,
    question: 'Which of the following is/are included in the Capital Budget of the Government of India?\n1. Expenditure on acquisition of assets like roads, buildings, machinery\n2. Loans received from foreign governments\n3. Loans and advances granted to the States and Union Territories',
    options: [
      { id: '0', text: '1 only' },
      { id: '1', text: '2 and 3 only' },
      { id: '2', text: '1 and 3 only' },
      { id: '3', text: '1, 2 and 3' },
    ],
    correctAnswer: '3',
    explanation: 'Capital Budget consists of Capital Receipts (market loans, foreign loans, recovery of loans) and Capital Expenditure (asset creation, repayment of borrowings, loans given to States). All 3 are part of Capital Budget.',
    difficulty: 'MEDIUM' as const,
    examTag: 'UPSC CSE Prelims PYQ',
    pyqYear: 2016,
    isPyq: true,
    source: 'UPSC CSE Prelims',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_econ_04',
    subjectId: 'sub_economy',
    topicId: 'top_banking',
    conceptId: 'c_mpc',
    type: 'MCQ' as const,
    question: 'The money multiplier in an economy increases with which one of the following?',
    options: [
      { id: '0', text: 'Increase in the Cash Reserve Ratio (CRR) in the banks' },
      { id: '1', text: 'Increase in the Statutory Liquidity Ratio (SLR) in the banks' },
      { id: '2', text: 'Increase in the banking habit of the population' },
      { id: '3', text: 'Increase in the population of the country' },
    ],
    correctAnswer: '2',
    explanation: 'Money multiplier is inversely proportional to reserve ratios and currency-to-deposit ratio. When banking habits increase, people keep less physical currency and more bank deposits, enabling banks to create more credit and raising the money multiplier.',
    difficulty: 'EASY' as const,
    examTag: 'UPSC CSE Prelims 2019 PYQ',
    pyqYear: 2019,
    isPyq: true,
    source: 'UPSC CSE 2019 Prelims',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },

  // HISTORY QUESTIONS (41-60)
  {
    id: 'q_hist_01',
    subjectId: 'sub_history',
    topicId: 'top_ancient',
    conceptId: 'c_art21',
    type: 'MCQ' as const,
    question: 'Which one of the following ancient towns is well-known for its elaborate system of water harvesting and management by building a series of dams and channelizing water into connected reservoirs?',
    options: [
      { id: '0', text: 'Dholavira' },
      { id: '1', text: 'Kalibangan' },
      { id: '2', text: 'Rakhigarhi' },
      { id: '3', text: 'Ropar' },
    ],
    correctAnswer: '0',
    explanation: 'Dholavira in the Rann of Kutch (Gujarat) is renowned for its grand rock-cut water reservoirs, check dams, and sophisticated stormwater drainage management.',
    difficulty: 'EASY' as const,
    examTag: 'UPSC CSE Prelims 2021 PYQ',
    pyqYear: 2021,
    isPyq: true,
    source: 'UPSC CSE 2021 Prelims Paper-1',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_hist_02',
    subjectId: 'sub_history',
    topicId: 'top_modern',
    conceptId: 'c_art32',
    type: 'MCQ' as const,
    question: 'With reference to the 8th August 1942 in Indian history, which one of the following statements is correct?',
    options: [
      { id: '0', text: 'The Quit India Resolution was adopted by the AICC at Bombay.' },
      { id: '1', text: 'The Cripps Mission arrived in India with constitutional proposals.' },
      { id: '2', text: 'Subhash Chandra Bose established the Indian National Army at Singapore.' },
      { id: '3', text: 'Wavell Plan was announced at the Simla Conference.' },
    ],
    correctAnswer: '0',
    explanation: 'On 8th August 1942, the All India Congress Committee (AICC) passed the Quit India Resolution at the Gowalia Tank Maidan in Bombay, where Mahatma Gandhi gave the "Do or Die" call.',
    difficulty: 'EASY' as const,
    examTag: 'UPSC CSE Prelims 2021 PYQ',
    pyqYear: 2021,
    isPyq: true,
    source: 'UPSC CSE 2021 Prelims Paper-1',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_hist_03',
    subjectId: 'sub_history',
    topicId: 'top_modern',
    conceptId: 'c_art32',
    type: 'MCQ' as const,
    question: 'In the context of Indian National Movement, the "Radcliffe Committee" was appointed to:',
    options: [
      { id: '0', text: 'Solve the problem of minorities in India' },
      { id: '1', text: 'Give effect to the Independence Bill' },
      { id: '2', text: 'Delimit the boundaries between India and Pakistan' },
      { id: '3', text: 'Enquire into the riots in East Bengal' },
    ],
    correctAnswer: '2',
    explanation: 'Sir Cyril Radcliffe chaired the Boundary Commissions appointed under the Indian Independence Act, 1947 to demarcate the international frontiers between India and East/West Pakistan.',
    difficulty: 'EASY' as const,
    examTag: 'UPSC CSE Prelims 2014 PYQ',
    pyqYear: 2014,
    isPyq: true,
    source: 'UPSC CSE Prelims',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },

  // GEOGRAPHY & ENVIRONMENT (61-80)
  {
    id: 'q_geo_01',
    subjectId: 'sub_geography',
    topicId: 'top_env',
    conceptId: 'c_art21',
    type: 'MCQ' as const,
    question: 'Which of the following are the UNESCO World Heritage Natural Sites located along the Western Ghats of India?\n1. Silent Valley National Park\n2. Kudremukh National Park\n3. Agasthyamalai Biosphere Reserve\n4. Simlipal National Park',
    options: [
      { id: '0', text: '1 and 2 only' },
      { id: '1', text: '1, 2 and 3 only' },
      { id: '2', text: '3 and 4 only' },
      { id: '3', text: '1, 2, 3 and 4' },
    ],
    correctAnswer: '1',
    explanation: 'Silent Valley, Kudremukh, and Agasthyamalai are located in the Western Ghats cluster inscribed as a UNESCO World Heritage Site. Simlipal is located in the Eastern Ghats / Mayurbhanj district of Odisha.',
    difficulty: 'MEDIUM' as const,
    examTag: 'UPSC CSE Prelims PYQ',
    pyqYear: 2022,
    isPyq: true,
    source: 'UPSC CSE 2022 Prelims',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_geo_02',
    subjectId: 'sub_geography',
    topicId: 'top_phys_geo',
    conceptId: 'c_art21',
    type: 'MCQ' as const,
    question: 'Consider the following rivers:\n1. Barak\n2. Lohit\n3. Subansiri\nWhich of the above flows/flow through Arunachal Pradesh?',
    options: [
      { id: '0', text: '1 only' },
      { id: '1', text: '2 and 3 only' },
      { id: '2', text: '1 and 3 only' },
      { id: '3', text: '1, 2 and 3' },
    ],
    correctAnswer: '1',
    explanation: 'Lohit and Subansiri originate in Tibet/Himalayas and flow through Arunachal Pradesh into the Brahmaputra. The Barak River rises in the Manipur hills and flows through Nagaland, Manipur, Mizoram and Assam without passing through Arunachal Pradesh.',
    difficulty: 'MEDIUM' as const,
    examTag: 'UPSC CSE Prelims 2014 PYQ',
    pyqYear: 2014,
    isPyq: true,
    source: 'UPSC CSE Prelims',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },

  // CURRENT AFFAIRS & BIHAR/UPSC GOVERNANCE (81-100)
  {
    id: 'q_ca_01',
    subjectId: 'sub_ca',
    topicId: 'top_monetary',
    conceptId: 'c_mpc',
    type: 'MCQ' as const,
    question: 'With reference to the Digital Rupee (e₹) or Central Bank Digital Currency (CBDC) launched by the Reserve Bank of India, consider the following statements:\n1. It is a sovereign currency issued by RBI in accordance with the RBI Act, 1934.\n2. It appears as a liability on RBI’s balance sheet.\n3. It requires an active commercial bank account to hold and transact retail CBDC.',
    options: [
      { id: '0', text: '1 and 2 only' },
      { id: '1', text: '2 and 3 only' },
      { id: '2', text: '1 and 3 only' },
      { id: '3', text: '1, 2 and 3' },
    ],
    correctAnswer: '0',
    explanation: 'Statements 1 and 2 are correct: CBDC is legal tender and a direct liability of the RBI. Statement 3 is incorrect because token-based retail CBDC (e₹-R) operates as a digital equivalent of cash and can be transacted via digital wallets without requiring direct bank account clearance for every transaction.',
    difficulty: 'HARD' as const,
    examTag: 'UPSC CSE Prelims 2023 PYQ',
    pyqYear: 2023,
    isPyq: true,
    source: 'UPSC Current Affairs & Economy 2023',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
  {
    id: 'q_bpsc_01',
    subjectId: 'sub_history',
    topicId: 'top_modern',
    conceptId: 'c_art32',
    type: 'MCQ' as const,
    question: 'Who led the Champaran Satyagraha in Bihar in 1917, which marked Mahatma Gandhi’s first civil disobedience movement in India?',
    options: [
      { id: '0', text: 'Dr. Rajendra Prasad' },
      { id: '1', text: 'Raj Kumar Shukla' },
      { id: '2', text: 'Mahatma Gandhi' },
      { id: '3', text: 'Anugrah Narayan Sinha' },
    ],
    correctAnswer: '2',
    explanation: 'Mahatma Gandhi led the Champaran Satyagraha in 1917 at the invitation of Raj Kumar Shukla to oppose the Tinkathia system imposed by European indigo planters.',
    difficulty: 'EASY' as const,
    examTag: 'BPSC Prelims PYQ',
    pyqYear: 2022,
    isPyq: true,
    source: 'BPSC 67th CCE Prelims',
    verifiedStatus: 'VERIFIED_PYQ' as const,
    isPublished: true,
  },
];

export async function ensureQuestionBankSeed(): Promise<void> {
  try {
    console.log('[Question Bank] Verifying question bank seed in PostgreSQL...');

    for (const q of VERIFIED_QUESTION_BANK) {
      await pool.query(`
        INSERT INTO public.questions (
          id, subject_id, topic_id, concept_id, type, question, question_en, question_hi,
          options, options_en, options_hi, correct_answer, explanation, explanation_en, explanation_hi,
          difficulty, exam_tag, pyq_year, is_pyq, source, verified_status, is_published, created_at
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8,
          $9::jsonb, $10::jsonb, $11::jsonb, $12, $13, $14, $15,
          $16, $17, $18, $19, $20, $21, $22, NOW()
        )
        ON CONFLICT (id) DO UPDATE SET
          question = EXCLUDED.question,
          options = EXCLUDED.options,
          correct_answer = EXCLUDED.correct_answer,
          explanation = EXCLUDED.explanation,
          is_published = true;
      `, [
        q.id,
        q.subjectId,
        q.topicId,
        q.conceptId,
        q.type,
        q.question,
        q.question_en || q.question,
        q.question_hi || null,
        JSON.stringify(q.options),
        JSON.stringify(q.options_en || q.options),
        q.options_hi ? JSON.stringify(q.options_hi) : null,
        q.correctAnswer,
        q.explanation,
        q.explanation_en || q.explanation,
        q.explanation_hi || null,
        q.difficulty,
        q.examTag,
        q.pyqYear,
        q.isPyq,
        q.source,
        q.verifiedStatus,
        q.isPublished,
      ]);
    }

    // Link standard questions to initial mock tests
    const mockLinks = [
      { mockId: 'mock_quick_1', qIds: ['q_polity_01', 'q_polity_02', 'q_polity_03', 'q_polity_04', 'q_polity_05', 'q_econ_01', 'q_econ_02', 'q_econ_03', 'q_econ_04', 'q_ca_01'] },
      { mockId: 'mock_subj_polity', qIds: ['q_polity_01', 'q_polity_02', 'q_polity_03', 'q_polity_04', 'q_polity_05'] },
    ];

    for (const link of mockLinks) {
      for (let i = 0; i < link.qIds.length; i++) {
        const qId = link.qIds[i];
        await pool.query(`
          INSERT INTO public.mock_questions (mock_test_id, question_id, order_num)
          VALUES ($1, $2, $3)
          ON CONFLICT (mock_test_id, question_id) DO UPDATE SET order_num = $3;
        `, [link.mockId, qId, i + 1]);
      }
    }

    console.log(`[Question Bank] Verified ${VERIFIED_QUESTION_BANK.length} authentic questions seeded in PostgreSQL.`);
  } catch (err: any) {
    console.error('[Question Bank] Seed error:', err.message);
  }
}
