import { Subject, Topic, Concept } from '../../src/types/index.js';

export const OFFICIAL_SUBJECTS: Subject[] = [
  {
    id: 'sub_polity',
    name: 'Indian Polity & Governance',
    code: 'POLITY',
    description: 'Indian Constitution, Fundamental Rights, Federal Structure, Parliament, Judiciary & Constitutional Bodies',
    iconName: 'Landmark',
    color: 'indigo',
    topicsCount: 6,
    conceptsCount: 14,
  },
  {
    id: 'sub_economy',
    name: 'Indian Economy & Banking',
    code: 'ECONOMY',
    description: 'Macroeconomics, Monetary Policy, Fiscal Federalism, Banking, Agriculture, Inflation & External Sector',
    iconName: 'TrendingUp',
    color: 'emerald',
    topicsCount: 5,
    conceptsCount: 12,
  },
  {
    id: 'sub_history',
    name: 'Indian History & Art / Culture',
    code: 'HISTORY',
    description: 'Ancient Civilizations, Medieval India, Modern Freedom Struggle 1757-1947, Architecture, Paintings & Heritage',
    iconName: 'Scroll',
    color: 'amber',
    topicsCount: 5,
    conceptsCount: 12,
  },
  {
    id: 'sub_geography',
    name: 'Geography (Physical, Human & India)',
    code: 'GEOGRAPHY',
    description: 'Geomorphology, Climatology, Oceanography, Indian Physiography, Drainage Systems & Resource Distribution',
    iconName: 'Compass',
    color: 'blue',
    topicsCount: 4,
    conceptsCount: 10,
  },
  {
    id: 'sub_environment',
    name: 'Environment, Ecology & Disaster Mgmt',
    code: 'ENVIRONMENT',
    description: 'Biodiversity Conservation, Protected Areas, Climate Change Conventions, Pollution Control & Disaster Risk Reduction',
    iconName: 'Leaf',
    color: 'teal',
    topicsCount: 4,
    conceptsCount: 9,
  },
  {
    id: 'sub_security_ir',
    name: 'Internal Security & International Relations',
    code: 'SECURITY_IR',
    description: 'Border Management, Cyber Security, Left Wing Extremism, Bilateral Ties, Quad, G20 & Global Groupings',
    iconName: 'Shield',
    color: 'cyan',
    topicsCount: 4,
    conceptsCount: 8,
  },
  {
    id: 'sub_ethics',
    name: 'Ethics, Integrity & Aptitude (GS-IV)',
    code: 'ETHICS',
    description: 'Human Values, Ethical Dilemmas in Administration, Emotional Intelligence, Probity in Governance & Case Studies',
    iconName: 'Scale',
    color: 'violet',
    topicsCount: 4,
    conceptsCount: 8,
  },
  {
    id: 'sub_bihar',
    name: 'Bihar Special: History, Geo, Economy & Polity',
    code: 'BIHAR_SPECIAL',
    description: '71st BPSC CCE Matrix: Ancient/Modern Bihar, Rivers & Soils, Economic Survey, Saat Nischay-2, Panchayati Raj & Art',
    iconName: 'BookOpen',
    color: 'orange',
    topicsCount: 6,
    conceptsCount: 15,
  },
  {
    id: 'sub_csat',
    name: 'CSAT & General Mental Ability',
    code: 'CSAT',
    description: 'Reading Comprehension, Logical Reasoning, Syllogisms, Basic Numeracy & Data Interpretation',
    iconName: 'Brain',
    color: 'rose',
    topicsCount: 3,
    conceptsCount: 6,
  },
  {
    id: 'sub_ca',
    name: 'Current Affairs & Governance',
    code: 'CURRENT_AFFAIRS',
    description: 'Daily PIB releases, Supreme Court Landmark Judgments, Science & Space Missions, Government Policies & Schemes',
    iconName: 'Newspaper',
    color: 'red',
    topicsCount: 4,
    conceptsCount: 10,
  },
];

export const OFFICIAL_TOPICS: Topic[] = [
  // Polity
  { id: 'top_const_framework', subjectId: 'sub_polity', name: 'Constitutional Framework & Preamble', description: 'Evolution, Salient Features, Preamble, Basic Structure Doctrine', order: 1, conceptsCount: 3 },
  { id: 'top_fundamental_rights', subjectId: 'sub_polity', name: 'Fundamental Rights, DPSPs & Duties', description: 'Articles 12-35, Directive Principles Part IV, Fundamental Duties Part IVA', order: 2, conceptsCount: 4 },
  { id: 'top_union_executive_parl', subjectId: 'sub_polity', name: 'Union Executive & Parliament', description: 'President, Prime Minister, Council of Ministers, Lok Sabha, Rajya Sabha & Lawmaking', order: 3, conceptsCount: 3 },
  { id: 'top_judiciary', subjectId: 'sub_polity', name: 'Judiciary, Writs & Judicial Review', description: 'Supreme Court, High Courts, Subordinate Courts, Collegium System, Judicial Activism', order: 4, conceptsCount: 3 },
  { id: 'top_federalism_local', subjectId: 'sub_polity', name: 'Federal Structure & Panchayati Raj', description: 'Union-State Relations, 73rd & 74th Amendments, Finance Commission, Inter-State Council', order: 5, conceptsCount: 2 },
  { id: 'top_const_bodies', subjectId: 'sub_polity', name: 'Constitutional & Statutory Bodies', description: 'ECI, CAG, UPSC, Finance Commission, NITI Aayog, NHRC, NGT', order: 6, conceptsCount: 2 },

  // Economy
  { id: 'top_monetary_banking', subjectId: 'sub_economy', name: 'Monetary Policy & Financial System', description: 'RBI, MPC, Repo Rate, Inflation Targeting, NPA Resolution, IBC & Digital Rupee', order: 1, conceptsCount: 3 },
  { id: 'top_fiscal_budget', subjectId: 'sub_economy', name: 'Fiscal Policy, Taxation & Budgeting', description: 'Union Budget, Fiscal Deficit, FRBM Act, Direct Taxes, GST & Fiscal Federalism', order: 2, conceptsCount: 3 },
  { id: 'top_agri_food', subjectId: 'sub_economy', name: 'Agriculture & Food Management', description: 'MSP, Cropping Patterns, Irrigation, Fertilizer Subsidy, PM-KISAN & PDS Reforms', order: 3, conceptsCount: 3 },
  { id: 'top_external_trade', subjectId: 'sub_economy', name: 'External Sector & Trade', description: 'Balance of Payments, Current Account Deficit, Forex Reserves, WTO & FTAs', order: 4, conceptsCount: 2 },
  { id: 'top_infra_industry', subjectId: 'sub_economy', name: 'Infrastructure, Industry & Growth', description: 'National Infrastructure Pipeline, PM GatiShakti, PLI Schemes, Logistics Policy', order: 5, conceptsCount: 2 },

  // History
  { id: 'top_ancient_india', subjectId: 'sub_history', name: 'Ancient India & Indus Valley Civilization', description: 'Harappan Urban Planning, Vedic Age, Mahajanapadas, Mauryan & Gupta Empires', order: 1, conceptsCount: 3 },
  { id: 'top_medieval_india', subjectId: 'sub_history', name: 'Medieval India & Art/Architecture', description: 'Delhi Sultanate, Mughal Administration, Vijayanagara Empire, Bhakti & Sufi Movements', order: 2, conceptsCount: 2 },
  { id: 'top_modern_freedom', subjectId: 'sub_history', name: 'Modern Indian Freedom Struggle (1757-1947)', description: '1857 Revolt, Moderate & Extremist Phases, Gandhian Movements, INA & Partition', order: 3, conceptsCount: 4 },
  { id: 'top_art_culture', subjectId: 'sub_history', name: 'Indian Art, Architecture & Culture', description: 'Temple Architecture (Nagara, Dravida, Vesara), Classical Dances, Paintings & UNESCO Sites', order: 4, conceptsCount: 3 },
  { id: 'top_post_independence', subjectId: 'sub_history', name: 'Post-Independence Consolidation', description: 'Integration of Princely States, Linguistic Reorganisation, Non-Aligned Movement', order: 5, conceptsCount: 1 },

  // Geography
  { id: 'top_physical_geography', subjectId: 'sub_geography', name: 'Physical Geography (Earth & Climate)', description: 'Plate Tectonics, Volcanism, Atmospheric Circulation, Monsoons, Cyclones & Ocean Currents', order: 1, conceptsCount: 3 },
  { id: 'top_indian_physiography', subjectId: 'sub_geography', name: 'Indian Physiography & Drainage', description: 'Himalayas, Northern Plains, Peninsular Plateau, Coastal Plains & River Systems', order: 2, conceptsCount: 3 },
  { id: 'top_resources_minerals', subjectId: 'sub_geography', name: 'Mineral & Energy Resources of India', description: 'Coal, Iron Ore, Critical Minerals (Lithium, Rare Earths), Renewable Potential', order: 3, conceptsCount: 2 },
  { id: 'top_human_economic_geo', subjectId: 'sub_geography', name: 'Human & Economic Geography', description: 'Demographics, Census trends, Urbanization, Migration & Industrial Corridors', order: 4, conceptsCount: 2 },

  // Environment
  { id: 'top_biodiversity_parks', subjectId: 'sub_environment', name: 'Biodiversity Conservation & Protected Areas', description: 'National Parks, Wildlife Sanctuaries, Biosphere Reserves, Ramsar Wetlands & Project Tiger', order: 1, conceptsCount: 3 },
  { id: 'top_climate_change_global', subjectId: 'sub_environment', name: 'Climate Change & Global Conventions', description: 'UNFCCC COP Agreements, Paris Pact, Net Zero Targets, Carbon Credits & IPCC Reports', order: 2, conceptsCount: 3 },
  { id: 'top_pollution_laws', subjectId: 'sub_environment', name: 'Pollution Control & Environmental Legislation', description: 'Air & Water Acts, Environment Protection Act 1986, Wildlife Protection Act 1972/2022 Amendment', order: 3, conceptsCount: 2 },
  { id: 'top_disaster_mgmt', subjectId: 'sub_environment', name: 'Disaster Management & Resilience', description: 'NDMA Guidelines, Sendai Framework, Flood Management & Earthquake Zoning', order: 4, conceptsCount: 2 },

  // Internal Security & IR
  { id: 'top_internal_security', subjectId: 'sub_security_ir', name: 'Internal Security Challenges', description: 'Left Wing Extremism, North East Insurgency, Terrorism & Coastal Security', order: 1, conceptsCount: 3 },
  { id: 'top_cyber_security', subjectId: 'sub_security_ir', name: 'Cyber Security & Financial Crimes', description: 'CERT-In, Critical Information Infrastructure, Money Laundering, PMLA & Hawala Networks', order: 2, conceptsCount: 2 },
  { id: 'top_bilateral_ties', subjectId: 'sub_security_ir', name: 'India’s Bilateral Relations', description: 'Neighbourhood First, Act East Policy, Indo-US Ties, India-Middle East Corridor', order: 3, conceptsCount: 2 },
  { id: 'top_global_groupings', subjectId: 'sub_security_ir', name: 'Multilateral Groupings & Global Order', description: 'G20, Quad, BRICS, SCO, UN Security Council Reforms & WTO Disputes', order: 4, conceptsCount: 2 },

  // Ethics (GS-IV)
  { id: 'top_ethics_human', subjectId: 'sub_ethics', name: 'Ethics and Human Interface', description: 'Essence, Determinants and Consequences of Ethics; Ethical Human Values & Lessons from Leaders', order: 1, conceptsCount: 2 },
  { id: 'top_attitude_ei', subjectId: 'sub_ethics', name: 'Attitude, Emotional Intelligence & Aptitude', description: 'Structure of Attitude, Moral & Political Attitudes, Emotional Intelligence in Administration', order: 2, conceptsCount: 2 },
  { id: 'top_probity_governance', subjectId: 'sub_ethics', name: 'Probity in Governance & Public Service Values', description: 'Civil Service Values, Code of Ethics, Citizen’s Charter, RTI & Work Culture', order: 3, conceptsCount: 2 },
  { id: 'top_case_studies', subjectId: 'sub_ethics', name: 'Administrative Case Studies & Decision Making', description: 'Conflict of Interest, Public Pressure, Corruption Whistleblowing & Disaster Response', order: 4, conceptsCount: 2 },

  // Bihar Special (71st BPSC)
  { id: 'top_bihar_ancient_medieval', subjectId: 'sub_bihar', name: 'Ancient & Medieval Bihar', description: 'Magadha Empire, Mauryas, Nalanda & Vikramshila Universities, Sher Shah Suri’s Governance', order: 1, conceptsCount: 3 },
  { id: 'top_bihar_freedom', subjectId: 'sub_bihar', name: 'Bihar in Freedom Movement (1857-1947)', description: 'Veer Kunwar Singh 1857, Champaran Satyagraha 1917, Swami Sahajanand & Kisan Sabha, Quit India 1942', order: 2, conceptsCount: 4 },
  { id: 'top_bihar_geography', subjectId: 'sub_bihar', name: 'Physical Geography, Rivers & Soils of Bihar', description: 'North & South Plains, Kosi, Gandak, Son, Falgu Rivers, Agro-Climatic Zones & Valmiki Tiger Reserve', order: 3, conceptsCount: 3 },
  { id: 'top_bihar_economy', subjectId: 'sub_bihar', name: 'Bihar Economy, Budget & Saat Nischay-2', description: 'Bihar Economic Survey, Agriculture Roadmap-4, Saat Nischay-2, Industrial Investment Promotion Policy', order: 4, conceptsCount: 3 },
  { id: 'top_bihar_polity_panchayat', subjectId: 'sub_bihar', name: 'Polity, Administration & Panchayati Raj in Bihar', description: 'Bihar Panchayati Raj Act 2006 (50% Women Reservation), Bihar Legislative Assembly, BPSC Administration', order: 5, conceptsCount: 2 },
  { id: 'top_bihar_art_culture', subjectId: 'sub_bihar', name: 'Art, Architecture & Folk Culture of Bihar', description: 'Patna Kalam Painting, Madhubani / Mithila Painting, Manjusha Art, Chhath Puja & Buddhist Circuit', order: 6, conceptsCount: 3 },

  // CSAT
  { id: 'top_reading_comp', subjectId: 'sub_csat', name: 'Reading Comprehension & Critical Reasoning', description: 'Crux, Assumptions, Inferences & Logical Deductions from Passages', order: 1, conceptsCount: 2 },
  { id: 'top_logical_reasoning', subjectId: 'sub_csat', name: 'Logical Reasoning & Analytical Puzzles', description: 'Syllogisms, Seating Arrangements, Blood Relations, Direction Sense & Coding-Decoding', order: 2, conceptsCount: 2 },
  { id: 'top_quant_data', subjectId: 'sub_csat', name: 'Quantitative Aptitude & Data Interpretation', description: 'Number Systems, Percentages, Ratios, Speed & Time, Permutations & Charts/Tables', order: 3, conceptsCount: 2 },

  // Current Affairs Topics
  { id: 'top_national_governance', subjectId: 'sub_ca', name: 'National Governance & Key Legislation', description: 'Parliamentary Acts, Data Protection Act, Bharatiya Nyaya Sanhita, Election Reforms', order: 1, conceptsCount: 3 },
  { id: 'top_science_space', subjectId: 'sub_ca', name: 'Science, Space & Emerging Technology', description: 'Gaganyaan, Chandrayaan-3 findings, Aditya-L1, Generative AI in Governance, Quantum Mission', order: 2, conceptsCount: 3 },
  { id: 'top_schemes_welfare', subjectId: 'sub_ca', name: 'Social Welfare Schemes & Indices', description: 'PM Vishwakarma, Jal Jeevan Mission, NITI Aayog Multidimensional Poverty Index', order: 3, conceptsCount: 2 },
  { id: 'top_bihar_ca', subjectId: 'sub_bihar', name: 'Bihar Special Current Affairs & State Policies', description: 'Bihar Caste Survey Implementation, Kosi-Mechi River Linkage, Bihar Tourism & Industrial Corridors', order: 4, conceptsCount: 3 },
];

export const OFFICIAL_CONCEPTS: Concept[] = [
  // --- POLITY CONCEPTS ---
  {
    id: 'c_basic_structure',
    subjectId: 'sub_polity',
    topicId: 'top_const_framework',
    title: 'Basic Structure Doctrine & Kesavananda Bharati (1973)',
    summary: 'The landmark constitutional principle that Parliament cannot alter the essential identity and core framework of the Indian Constitution under Article 368.',
    explanation: 'Propounded by a 13-judge bench of the Supreme Court in Kesavananda Bharati v. State of Kerala (1973). While Parliament possesses wide amending powers under Article 368, it cannot damage or destroy basic features such as Supremacy of the Constitution, Republican and Democratic form of Government, Secular character, Separation of Powers, Judicial Review, and Federalism. Reinforced in Minerva Mills (1980) and IR Coelho (2007).',
    examples: ['Striking down of NJAC (99th Amendment) in 2015 for violating Judicial Independence as a Basic Feature', 'Minerva Mills (1980) invalidating clauses curtailing judicial review'],
    keyPoints: [
      'Originates from German jurist Prof. Dietrich Conrad, first introduced into Indian jurisprudence in Golaknath (1967) and established in Kesavananda Bharati (1973).',
      'Basic features are not exhaustively defined in the text of the Constitution; they are determined case-by-case by the Supreme Court.',
      'Acts placed in the Ninth Schedule after April 24, 1973, are open to judicial review if they violate fundamental rights forming part of the basic structure (I.R. Coelho Case 2007).',
    ],
    difficulty: 'ADVANCED',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_art21', 'c_art32'],
    tags: ['Polity', 'Constitutional Law', 'Supreme Court', 'Amendments', 'GS-2'],
  },
  {
    id: 'c_preamble_values',
    subjectId: 'sub_polity',
    topicId: 'top_const_framework',
    title: 'Preamble: Key Adjectives, Objectives & Legal Status',
    summary: 'The philosophical soul of the Constitution detailing India’s sovereign character and the four cardinal goals: Justice, Liberty, Equality, and Fraternity.',
    explanation: 'Adopted from the Objective Resolution drafted by Pandit Jawaharlal Nehru on December 13, 1946. Declares India as a "Sovereign Socialist Secular Democratic Republic". The 42nd Constitutional Amendment Act (1976) added three words: "Socialist", "Secular", and "Integrity". In Kesavananda Bharati (1973) and LIC of India (1995), the Supreme Court ruled that the Preamble is an integral part of the Constitution, can be amended under Article 368 (without altering basic structure), but is non-justiciable in a court of law.',
    examples: ['SR Bommai Case (1994) ruling secularism is a basic feature of the Constitution.', 'Indra Sawhney Case on equality of opportunity and social justice.'],
    keyPoints: [
      'Non-justiciable: Provisions of Preamble are not directly enforceable in courts of law.',
      'Source of power: Preamble is neither a source of power to the legislature nor a prohibition upon legislative powers.',
      'Enactment date specified in text: November 26, 1949.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_basic_structure'],
    tags: ['Polity', 'Preamble', 'Constitution', 'GS-2'],
  },
  {
    id: 'c_art21',
    subjectId: 'sub_polity',
    topicId: 'top_fundamental_rights',
    title: 'Article 21: Protection of Life and Personal Liberty & Expanded Horizons',
    summary: 'Guarantees the fundamental right to life and personal liberty, interpreted dynamically to encompass human dignity, privacy, and livelihood.',
    explanation: 'Article 21 states: "No person shall be deprived of his life or personal liberty except according to procedure established by law." In AK Gopalan (1950), the court took a narrow view. In Maneka Gandhi (1978), the Supreme Court ruled that the procedure must be "just, fair, and reasonable", incorporating American "due process of law". The golden triangle (Articles 14, 19, and 21) was established. In KS Puttaswamy (2017), a 9-judge bench unanimously recognized the Right to Privacy as an intrinsic part of Article 21.',
    examples: ['Right to Privacy (KS Puttaswamy 2017)', 'Right to Clean Environment (Subhash Kumar 1991)', 'Right to Die with Dignity / Passive Euthanasia (Common Cause 2018)'],
    keyPoints: [
      'Available to both Indian citizens and foreign nationals.',
      'Cannot be suspended even during a National Emergency under Article 352 (via 44th Amendment Act 1978).',
      'Article 21A (Right to Free & Compulsory Education for children aged 6-14) was inserted via the 86th Amendment Act 2002.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_art32', 'c_art226'],
    tags: ['Polity', 'Fundamental Rights', 'Judiciary', 'GS-2'],
  },
  {
    id: 'c_art32',
    subjectId: 'sub_polity',
    topicId: 'top_judiciary',
    title: 'Article 32: Right to Constitutional Remedies & Supreme Court Writs',
    summary: 'Termed by Dr. B.R. Ambedkar as the "Heart and Soul" of the Constitution, granting citizens direct access to the Supreme Court for fundamental right enforcement.',
    explanation: 'Conveys original jurisdiction to the Supreme Court to issue 5 prerogative writs: Habeas Corpus (produce the body), Mandamus (we command public duty), Prohibition (prevent lower tribunal from exceeding jurisdiction), Certiorari (quash order of lower tribunal), and Quo-Warranto (by what warrant/authority). The right to petition the Supreme Court is itself a Fundamental Right under Part III.',
    examples: ['Habeas corpus writ filed in preventive detention cases', 'Mandamus issued to civic authorities to clear public drainage/garbage'],
    keyPoints: [
      'Supreme Court cannot refuse to entertain an Article 32 petition if a Fundamental Right is demonstrably violated.',
      'Article 32 is strictly limited to the enforcement of Fundamental Rights in Part III.',
      'Can be suspended during National Emergency under Article 359 by Presidential order.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: ['c_art21'],
    relatedIds: ['c_art226'],
    tags: ['Polity', 'Writs', 'Supreme Court', 'GS-2'],
  },
  {
    id: 'c_art226',
    subjectId: 'sub_polity',
    topicId: 'top_judiciary',
    title: 'Article 226: High Court Writ Jurisdiction & Comparative Scope',
    summary: 'Empowers High Courts to issue directions, orders, or writs for enforcing Fundamental Rights as well as ordinary legal and statutory rights.',
    explanation: 'Article 226 provides High Courts with writ power for "the enforcement of any of the rights conferred by Part III and for any other purpose". Hence, in terms of subject matter scope, Article 226 is wider than Article 32. In Chandra Kumar (1997), the Supreme Court held that the writ power of High Courts under Article 226 is part of the basic structure and cannot be excluded by administrative tribunals.',
    examples: ['Enforcing statutory consumer or municipal rights against a state agency', 'Challenging university examination arbitrary decisions'],
    keyPoints: [
      'High Court writ jurisdiction is discretionary; petitioner can be directed to exhaust alternative legal remedies first.',
      'Territorial jurisdiction exists throughout the territory in relation to which it exercises jurisdiction or where the cause of action wholly or partially arises.',
      'Writ under Article 226 is a constitutional remedy, but not itself a fundamental right unlike Article 32.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: ['c_art32'],
    relatedIds: ['c_art32'],
    tags: ['Polity', 'High Court', 'Writs', 'GS-2'],
  },
  {
    id: 'c_collegium_system',
    subjectId: 'sub_polity',
    topicId: 'top_judiciary',
    title: 'Collegium System for Judicial Appointments & Three Judges Cases',
    summary: 'The judge-led mechanism for appointing and transferring judges to the Supreme Court and High Courts developed through judicial interpretation.',
    explanation: 'Evolution: First Judges Case (1981) held Executive primacy; Second Judges Case (1993) introduced the Collegium where "consultation" means "concurrence" and CJI + 2 senior-most judges recommend; Third Judges Case (1998 Presidential Reference) expanded SC Collegium to CJI + 4 senior-most judges. The 99th Constitutional Amendment created the National Judicial Appointments Commission (NJAC), which was struck down by the Supreme Court in 2015 for infringing Judicial Independence.',
    examples: ['Recommendation of High Court Chief Justices by Supreme Court Collegium', 'Ongoing debates around Memorandum of Procedure (MoP)'],
    keyPoints: [
      'Collegium is not mentioned in the original text of the Indian Constitution.',
      'SC Collegium consists of 5 members: Chief Justice of India + 4 senior-most judges of Supreme Court.',
      'High Court Collegium consists of Chief Justice of HC + 2 senior-most HC judges.',
    ],
    difficulty: 'ADVANCED',
    importance: 'HIGH',
    prerequisiteIds: ['c_art32'],
    relatedIds: ['c_basic_structure'],
    tags: ['Polity', 'Judiciary', 'Appointments', 'GS-2'],
  },
  {
    id: 'c_fiscal_fed',
    subjectId: 'sub_polity',
    topicId: 'top_federalism_local',
    title: 'Fiscal Federalism, Vertical/Horizontal Devolution & GST Council',
    summary: 'The institutional framework governing division of taxation powers, revenue sharing, grants-in-aid, and consensus-based indirect tax governance.',
    explanation: 'Articles 268 to 293 govern financial relations between Union and States. Because the Union has higher revenue buoyancy while States incur substantial social infrastructure expenditures, vertical fiscal imbalance is corrected via the Finance Commission (Article 280). The 101st Amendment Act established the Goods and Services Tax (GST) Council under Article 279A, functioning on cooperative federalism (Union has 1/3 weightage, States have 2/3 weightage, requiring 75% majority).',
    examples: ['15th Finance Commission formula allocating 41% net tax divisible pool to States', 'GST Council compensation cess discussions'],
    keyPoints: [
      'Finance Commission recommends Vertical Devolution (Union to States) and Horizontal Devolution (inter-se distribution among States).',
      'Article 275 mandates statutory Grants-in-Aid charged on Consolidated Fund of India.',
      'Article 282 provides for discretionary grants for public purposes.',
    ],
    difficulty: 'ADVANCED',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_fin_comm', 'c_mpc'],
    tags: ['Polity', 'Economy', 'Federalism', 'GST', 'GS-2', 'GS-3'],
  },
  {
    id: 'c_panchayati_raj_73',
    subjectId: 'sub_polity',
    topicId: 'top_federalism_local',
    title: '73rd & 74th Constitutional Amendments: Local Self-Government',
    summary: 'Constitutionalisation of rural and urban local bodies creating a 3-tier decentralized governance framework with mandatory reservations.',
    explanation: 'Enacted in 1992 based on recommendations of Balwant Rai Mehta (1957), Ashok Mehta (1977), and LM Singhvi (1986) committees. Inserted Part IX (Articles 243 to 243O) and Eleventh Schedule (29 functional items) for Panchayats, and Part IXA (Articles 243P to 243ZG) and Twelfth Schedule (18 functional items) for Municipalities. Mandates 3-tier structure (Gram, Intermediate, District), mandatory 1/3rd reservation for women, State Finance Commission (243-I), and State Election Commission (243-K).',
    examples: ['Bihar was the first state in India to mandate 50% reservation for women in Panchayati Raj Institutions (2006)', 'Social audits conducted through Gram Sabha'],
    keyPoints: [
      'Gram Sabha (Article 243A) is the foundation of the Panchayati Raj system, comprising all registered voters in the village.',
      'Term of Panchayats is 5 years; fresh elections must be held before expiration or within 6 months of dissolution.',
      'Panchayats (Extension to Scheduled Areas) Act (PESA) 1996 extends Part IX to Fifth Schedule areas with special powers to Gram Sabhas.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_fiscal_fed', 'c_bihar_panchayat_2006'],
    tags: ['Polity', 'Panchayati Raj', 'Decentralization', 'GS-2'],
  },

  // --- ECONOMY CONCEPTS ---
  {
    id: 'c_mpc',
    subjectId: 'sub_economy',
    topicId: 'top_monetary_banking',
    title: 'Monetary Policy Committee (MPC) & Flexible Inflation Targeting',
    summary: 'Statutory 6-member committee under the RBI Act, 1934 tasked with determining the policy repo rate to achieve the 4% (+/-2%) CPI inflation target.',
    explanation: 'Instituted in 2016 following the Urjit Patel Committee recommendations. Comprises 6 members: 3 from RBI (RBI Governor as ex-officio Chairperson, Deputy Governor in-charge of monetary policy, and one RBI officer) and 3 external members nominated by the Central Government. The MPC meets at least 4 times a year. Decisions are taken by majority vote; in case of a tie, the RBI Governor has a second casting vote.',
    examples: ['Bimonthly MPC resolutions adjusting policy repo rate to manage headline retail inflation', 'Stance of withdrawal of accommodation vs neutral stance'],
    keyPoints: [
      'Primary objective: Maintain price stability while keeping in mind the objective of growth.',
      'Inflation target: 4% Consumer Price Index (CPI) Combined with a tolerance band of +/- 2% (2% to 6%).',
      'Failure to maintain target: If average inflation is outside the tolerance band for three consecutive quarters, RBI must submit a report to the Central Govt stating causes and remedial actions.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_fin_comm', 'c_fiscal_fed'],
    tags: ['Economy', 'Monetary Policy', 'RBI', 'Inflation', 'GS-3'],
  },
  {
    id: 'c_fin_comm',
    subjectId: 'sub_economy',
    topicId: 'top_fiscal_budget',
    title: 'Finance Commission of India (Article 280) & 16th FC Terms',
    summary: 'Constitutional quasi-judicial body constituted every 5 years to recommend the formula for sharing Central tax proceeds with States.',
    explanation: 'Mandated by Article 280. Appointed by the President. Consists of a Chairman and 4 other members. Key functions: (1) Distribution of net proceeds of taxes between Union and States (Vertical), (2) Allocation between States of respective shares (Horizontal), (3) Principles governing Grants-in-Aid under Article 275, (4) Measures to augment Consolidated Fund of a State to supplement resources of Panchayats and Municipalities. 15th FC (chaired by NK Singh) recommended 41% vertical devolution.',
    examples: ['16th Finance Commission constituted under chairmanship of Dr. Arvind Panagariya in Dec 2023 for the award period 2026-31', 'Criteria: Income distance, Area, Population (2011 census), Forest & Ecology, Demographic Performance, Tax effort'],
    keyPoints: [
      'Recommendations of the Finance Commission are advisory in nature, though conventionally accepted by the Government.',
      '15th FC switched to 2011 Census population data exclusively, introducing "Demographic Performance" criterion to reward states with lower fertility rates.',
      'Finance Commission reports are laid before both Houses of Parliament along with an Explanatory Memorandum on action taken.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: ['c_fiscal_fed'],
    relatedIds: ['c_fiscal_fed', 'c_mpc'],
    tags: ['Economy', 'Fiscal Federalism', 'Finance Commission', 'GS-3'],
  },
  {
    id: 'c_msp_agri',
    subjectId: 'sub_economy',
    topicId: 'top_agri_food',
    title: 'Minimum Support Price (MSP), CACP Formulas & Open-Ended Procurement',
    summary: 'Agricultural price support mechanism announced by the Government before sowing seasons to insure farmers against steep falls in farm prices.',
    explanation: 'Recommended by the Commission for Agricultural Costs and Prices (CACP) and approved by the Cabinet Committee on Economic Affairs (CCEA). Announced for 22 mandated crops (14 Kharif, 6 Rabi, 2 commercial) plus Fair and Remunerative Price (FRP) for Sugarcane. Cost concepts: A2 (actual paid-out costs), A2+FL (paid-out costs + imputed value of family labour), and C2 (comprehensive cost including rental value of owned land and interest on capital). Government committed in 2018-19 Budget to set MSP at minimum 1.5 times (A2+FL).',
    examples: ['Procurement of paddy and wheat by Food Corporation of India (FCI) for the Central Pool', 'Pradhan Mantri Annadata Aay Sanrakshan Abhiyan (PM-AASHA)'],
    keyPoints: [
      'CACP is an attached office of the Ministry of Agriculture and Farmers Welfare, established in 1965.',
      'MSP has statutory backing only through executive notification, not via an explicit Act of Parliament.',
      'Factors considered: Cost of production, changes in input prices, demand-supply situation, inter-crop price parity, and effect on inflation and consumer cost of living.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_mpc'],
    tags: ['Economy', 'Agriculture', 'CACP', 'Food Security', 'GS-3'],
  },

  // --- HISTORY CONCEPTS ---
  {
    id: 'c_mauryan_empire',
    subjectId: 'sub_history',
    topicId: 'top_ancient_india',
    title: 'Mauryan Empire: Administration, Ashoka’s Dhamma & Edicts',
    summary: 'India’s first pan-Indian empire (322-185 BCE) renowned for Kautilya’s Arthashastra, centralized bureaucracy, rock edicts, and Buddhist patronship.',
    explanation: 'Founded by Chandragupta Maurya with guidance from Chanakya (Kautilya). Reached its zenith under Emperor Ashoka. Ashoka’s 14 Major Rock Edicts, Minor Rock Edicts, and Pillar Edicts (written in Prakrit/Brahmi, Kharosthi, Greek, and Aramaic) propagated Dhamma—a code of ethical conduct emphasizing non-violence (Ahimsa), religious tolerance, filial piety, and welfare state principles. Mauryan art introduced monolithic stone pillars with lustrous polish (e.g. Sarnath Lion Capital, Rampurva Bull).',
    examples: ['Major Rock Edict XIII detailing remorse over Kalinga War (261 BCE)', 'Kautilya’s Saptanga Theory of State (Swami, Amatya, Janapada, Durga, Kosha, Danda, Mitra)'],
    keyPoints: [
      'Megasthenes, the Greek ambassador sent by Seleucus Nicator, authored Indica describing Pataliputra municipal administration.',
      'Pillar inscriptions at Lauriya Nandangarh, Lauriya Areraj, and Rampurva in West Champaran, Bihar.',
      'Ashoka appointed Dhamma Mahamattas to propagate moral conduct and welfare.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_bihar_ancient_magadha', 'c_patna_kalam'],
    tags: ['History', 'Ancient India', 'Mauryas', 'Ashoka', 'Bihar', 'GS-1'],
  },
  {
    id: 'c_champaran_1917',
    subjectId: 'sub_history',
    topicId: 'top_modern_freedom',
    title: 'Champaran Satyagraha (1917): Gandhi’s First Civil Disobedience in India',
    summary: 'Mahatma Gandhi’s first successful non-violent satyagraha in India, launched against the oppressive Tinkathia system forced on indigo ryots in Bihar.',
    explanation: 'European planters forced Champaran peasants under the Tinkathia system to cultivate indigo on 3/20th part of their best land. Raj Kumar Shukla persuaded Gandhi at the 1916 Lucknow Congress session to visit Champaran. Joined by Dr. Rajendra Prasad, Brajkishore Prasad, Mazhar-ul-Haq, Acharya JB Kripalani, and Anugrah Narayan Sinha. Gandhi defied the district magistrate’s order to leave, was appointed to the Champaran Agrarian Committee, and successfully abolished Tinkathia with a 25% refund of illegal exactions.',
    examples: ['Formation of Champaran Agrarian Act 1918', 'Rabindranath Tagore bestowing the title "Mahatma" upon Gandhi after the Champaran success'],
    keyPoints: [
      'Marked the transformation of Indian national movement from elite debates to mass participation.',
      'First civil disobedience laboratory validating passive resistance and truth/non-violence techniques.',
      'Established Gandhi as the undisputed mass leader of the Indian national struggle.',
    ],
    difficulty: 'BEGINNER',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_bihar_freedom_1857', 'c_bihar_kisan_sabha'],
    tags: ['History', 'Modern India', 'Champaran', 'Gandhi', 'Bihar Special', 'GS-1'],
  },

  // --- GEOGRAPHY CONCEPTS ---
  {
    id: 'c_indian_monsoon',
    subjectId: 'sub_geography',
    topicId: 'top_physical_geography',
    title: 'Mechanism of Indian Monsoon: ITCZ, Jet Streams & ENSO Dynamics',
    summary: 'The seasonal reversal of wind patterns governed by differential heating, Tibetan Plateau thermal low, Tropical Easterly Jet, El Niño/La Niña, and IOD.',
    explanation: 'During summer, the Inter-Tropical Convergence Zone (ITCZ) shifts northward to the foothills of the Himalayas (Monsoon Trough). Heating of the Tibetan Plateau generates an upper-tropospheric anti-cyclone, strengthening the Tropical Easterly Jet (TEJ) and Somali Jet (Findlater Jet). Oceanic teleconnections: El Niño (warm phase of ENSO in equatorial Pacific) generally suppresses Indian monsoons, while La Niña enhances rainfall. Positive Indian Ocean Dipole (IOD) aids the southwest monsoon.',
    examples: ['Southwest Monsoon (June-Sept) contributing over 75% of India’s annual precipitation', 'Retreating / Northeast Monsoon bringing winter rains to Tamil Nadu and Coromandel coast'],
    keyPoints: [
      'Two main branches of Southwest Monsoon: Arabian Sea branch and Bay of Bengal branch.',
      'Mascarene High (high-pressure cell over south Indian Ocean near Madagascar) acts as the driving source of cross-equatorial monsoon winds.',
      'Madden-Julian Oscillation (MJO) is an eastward moving pulse of cloud and rainfall that enhances monsoon activity during its passage over the Indian Ocean.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_bihar_geo_rivers'],
    tags: ['Geography', 'Climatology', 'Monsoon', 'ENSO', 'GS-1'],
  },

  // --- BIHAR SPECIAL CONCEPTS (71st BPSC CCE) ---
  {
    id: 'c_bihar_ancient_magadha',
    subjectId: 'sub_bihar',
    topicId: 'top_bihar_ancient_medieval',
    title: 'Magadha Empire: Haryanka, Shishunaga, Nanda, Nalanda & Vikramshila',
    summary: 'The epicentre of ancient Indian imperial power, Jainism, Buddhism, and world-renowned monastic universities in the middle Gangetic plain.',
    explanation: 'Magadha rose to prominence under Bimbisara and Ajatashatru (Haryanka dynasty), who established capitals at Rajgir (Girivraja) and Pataliputra. Followed by the Shishunagas, Nandas, Mauryas, and Guptas. Bihar served as the birthplace of Buddhism (Bodh Gaya enlightenment of Gautama Buddha) and Jainism (birth of Lord Mahavira at Kundagram, Vaishali). Nalanda Mahavihara (founded by Kumaragupta I) and Vikramshila University (founded by Dharmapala) attracted scholars from China (Xuanzang, Faxian), Tibet, and Korea.',
    examples: ['First Buddhist Council at Sattapanni Cave, Rajgir (483 BCE) under Ajatashatru', 'Second Buddhist Council at Vaishali (383 BCE) under Kalashoka', 'Third Buddhist Council at Pataliputra (250 BCE) under Ashoka'],
    keyPoints: [
      'Vaishali is recognized as the world’s first republican state (Vajji Mahajanapada / Lichhavis).',
      'Nalanda University was destroyed by Bakhtiyar Khilji in 1193 CE; revived as Nalanda International University in Rajgir.',
      'Sher Shah Suri built the Grand Trunk Road (Sadak-e-Azam) and established his mausoleum at Sasaram, Bihar.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_mauryan_empire', 'c_patna_kalam'],
    tags: ['Bihar Special', 'BPSC', 'Ancient History', 'Nalanda', 'Magadha', 'GS-1'],
  },
  {
    id: 'c_bihar_freedom_1857',
    subjectId: 'sub_bihar',
    topicId: 'top_bihar_freedom',
    title: 'Veer Kunwar Singh & the 1857 Revolt in Bihar',
    summary: 'The 80-year-old Zamindar of Jagdishpur who led the Bihar uprising against British colonial forces with unmatched guerilla tactics.',
    explanation: 'The 1857 revolt in Bihar began on June 12, 1857, at Rohini village (Deoghar, now in Jharkhand) by soldiers of the 32nd Native Infantry. In Patna, Pir Ali Khan (a bookseller) led the rebellion on July 3, 1857. On July 25, 1857, the Danapur sepoys mutinied and joined Veer Kunwar Singh of Jagdishpur (Bhojpur). Despite being 80 years old, Kunwar Singh captured Arrah, defeated Captain Dunbar, and liberated Azamgarh (UP) before defeating Captain Le Grand at Jagdishpur in April 1858.',
    examples: ['Kunwar Singh severed his own injured arm and offered it to the River Ganga during the retreat across the river', 'Amar Singh (brother of Kunwar Singh) continued guerilla warfare in Kaimur hills'],
    keyPoints: [
      'Kunwar Singh was hailed as the "Babu" of Jagdishpur and the Grand Old Hero of 1857.',
      'Commissioner William Tayler suppressed the Patna uprising and hanged Pir Ali Khan.',
      'Bihar Government celebrates April 23 as "Vijayotsav" in honour of Veer Kunwar Singh’s victory over British forces.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_champaran_1917', 'c_bihar_kisan_sabha'],
    tags: ['Bihar Special', 'BPSC', '1857 Revolt', 'Kunwar Singh', 'Freedom Struggle', 'GS-1'],
  },
  {
    id: 'c_bihar_kisan_sabha',
    subjectId: 'sub_bihar',
    topicId: 'top_bihar_freedom',
    title: 'Swami Sahajanand Saraswati & Bihar Provincial Kisan Sabha (1929)',
    summary: 'The founding leader of the peasant movement in India who mobilized millions of ryots against the Zamindari system and feudal oppressions.',
    explanation: 'Swami Sahajanand Saraswati formed the Bihar Provincial Kisan Sabha (BPKS) in 1929 at the Sonepur Fair to resist landlord atrocities, illegal cesses (Abwabs), and eviction from Bakasht lands. Prominent leaders included Karyanand Sharma (Barahiya Tal satyagraha), Rahul Sankrityayan (Annawari satyagraha), Yadunandan Sharma (Reora satyagraha), and Jamun Karjee. In 1936, the All India Kisan Sabha (AIKS) was established at Lucknow with Swami Sahajanand as President and NG Ranga as General Secretary.',
    examples: ['Bakasht Movement in Barahiya Tal (Monghyr district) led by Karyanand Sharma (1937-39)', 'Weekly Kisan journal "Hunkar" published from Patna'],
    keyPoints: [
      'Swami Sahajanand established his ashram at Bihta near Patna.',
      'Bihar Socialist Party was formed in 1931 by Ganga Sharan Sinha, Rambriksh Benipuri, and Ramanand Mishra.',
      'Congress Socialist Party was formally founded in 1934 at Anjuman Islamia Hall, Patna, with Acharya Narendra Deva as President and Jayaprakash Narayan as General Secretary.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: ['c_champaran_1917'],
    relatedIds: ['c_bihar_quit_india_1942'],
    tags: ['Bihar Special', 'BPSC', 'Kisan Sabha', 'Sahajanand', 'Peasant Movement', 'GS-1'],
  },
  {
    id: 'c_bihar_quit_india_1942',
    subjectId: 'sub_bihar',
    topicId: 'top_bihar_freedom',
    title: 'Quit India Movement (1942) in Bihar: Secretariat Martyrdom & Azad Dasta',
    summary: 'Massive popular rebellion in Bihar marked by the martyrdom of seven young students in Patna and underground resistance led by Jayaprakash Narayan.',
    explanation: 'Following Gandhi’s "Do or Die" call on August 8, 1942, British authorities arrested top leaders in Patna including Dr. Rajendra Prasad (jailed at Bankipur). On August 11, 1942, seven brave school and college students (Umakant Prasad Sinha, Ramanand Singh, Satish Prasad Jha, Jagatpati Kumar, Devi Pado Choudhury, Rajendra Singh, Ramgovind Singh) were shot dead while hoisting the tricolour at the Patna Secretariat by order of District Magistrate WG Archer. Jayaprakash Narayan escaped from Hazaribagh Jail on Diwali night 1942 and formed the underground guerilla force "Azad Dasta" in the Terai region of Nepal to disrupt communications and British logistics.',
    examples: ['Martyrs’ Memorial (Shaheed Smarak) erected in front of the Bihar Vidhan Sabha, Patna', 'Parallel government (Jatiya Sarkar) formed in parts of Bihar during the 1942 revolt'],
    keyPoints: [
      'Radio broadcast by Usha Mehta and Rammanohar Lohia supported underground resistance.',
      'Azad Dasta trained youth in guerilla warfare, sabotage of railway lines, and telegraph wires.',
      'Siwan became a major hub where Phulena Prasad Srivastava achieved martyrdom while hoisting the national flag at the police station.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: ['c_bihar_kisan_sabha'],
    relatedIds: ['c_champaran_1917'],
    tags: ['Bihar Special', 'BPSC', 'Quit India', '1942', 'Jayaprakash Narayan', 'GS-1'],
  },
  {
    id: 'c_bihar_geo_rivers',
    subjectId: 'sub_bihar',
    topicId: 'top_bihar_geography',
    title: 'Physiography, River Systems & Agro-Climatic Zones of Bihar',
    summary: 'The geological divisions, perennial Himalayan and peninsular river drainage networks, and 3 distinct agro-climatic zones of Bihar.',
    explanation: 'Physiographically, Bihar consists of: (1) Shiwalik Hilly Region (Someshwar Range in West Champaran), (2) Bihar Plain (North & South Ganga Plain covering 95% of state area), and (3) Southern Hilly/Plateau Region (Kaimur, Rohtas, Gaya, Rajgir, Jamui, Banka). River Ganga enters Bihar at Chausa (Buxar) and flows 445 km through 12 districts before exiting at Manihari (Katihar). North Himalayan tributaries: Ghaghara, Gandak, Bagmati, Kamla, Kosi ("Sorrow of Bihar"), and Mahananda. South tributaries: Karmanasa, Son, Punpun, Falgu (Lilajan), Kiul, and Chandan.',
    examples: ['Kosi river originating from Tibet/Nepal joins Ganga at Kursela (Katihar)', 'Son river originating from Amarkantak (MP) joins Ganga near Maner/Patna', 'Falgu river in Gaya where world’s longest rubber dam (Gayaji Dam) is constructed'],
    keyPoints: [
      'Agro-Climatic Zones: Zone I (North-West alluvial plain, 13 districts), Zone II (North-East alluvial plain, 8 districts), Zone III-A (South-East alluvial plain, 6 districts), Zone III-B (South-West alluvial plain, 11 districts).',
      'Valmiki National Park & Tiger Reserve is situated in West Champaran along the Gandak River (Bihar’s only National Park; second tiger reserve approved in Kaimur).',
      'Kanwar Lake (Kabartal) in Begusarai is Bihar’s first Ramsar Wetland of International Importance (2020).',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: ['c_indian_monsoon'],
    relatedIds: ['c_bihar_economy_saat_nischay'],
    tags: ['Bihar Special', 'BPSC', 'Geography', 'Ganga', 'Rivers', 'Agro-Climatic', 'GS-1', 'GS-2'],
  },
  {
    id: 'c_bihar_economy_saat_nischay',
    subjectId: 'sub_bihar',
    topicId: 'top_bihar_economy',
    title: 'Bihar Economy, Economic Survey 2025-26 & Saat Nischay-2 Framework',
    summary: 'The macroeconomic trajectory of Bihar, Agriculture Road Map-4, and the flagship 7-point developmental charter for holistic socio-economic transformation.',
    explanation: 'Bihar’s Gross State Domestic Product (GSDP) has maintained strong growth driven by tertiary (services) and primary (agriculture) sectors. Flagship Saat Nischay Part-2 (2020-2025) pillars: (1) Yuva Shakti - Bihar Ki Pragati (Skill development, Mega Skill Centres), (2) Sashakt Mahila - Samriddh Mahila (Financial aid for female graduates and entrepreneurs), (3) Har Khet Tak Sinchai Ka Paani (Assured irrigation for every farmland), (4) Swachh Gaon - Samriddh Gaon (Solar street lights, solid waste management), (5) Swachh Shahar - Viksit Shahar (Stormwater drainage, elderly shelters), (6) Sulabh Samparkata (Bypass roads and flyovers), and (7) Sabke Liye Swasthya Suvidha (Telemedicine, upgraded CHCs/PHCs).',
    examples: ['Mukhyamantri Udyami Yojana providing ₹10 lakh loan-cum-subsidy to SC/ST/EBC/Women/Youth entrepreneurs', 'Jal-Jeevan-Hariyali Mission recognized at international COP climate platforms'],
    keyPoints: [
      'Agriculture Road Map-4 (2023-2028) emphasizes organic farming corridors along the Ganga, millet promotion, climate-resilient agriculture, and cold-chain logistics.',
      'Bihar Industrial Investment Promotion Policy offers capital subsidy, interest subvention, and stamp duty exemption for food processing, textiles, ethanol, and IT.',
      'Mithila Makhana (Foxnut), Shahi Litchi of Muzaffarpur, Katarni Rice, Magahi Paan, and Zardalu Mango hold protected Geographical Indication (GI) tags.',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_bihar_geo_rivers', 'c_fiscal_fed'],
    tags: ['Bihar Special', 'BPSC', 'Economy', 'Saat Nischay', 'Economic Survey', 'GS-2'],
  },
  {
    id: 'c_bihar_panchayat_2006',
    subjectId: 'sub_bihar',
    topicId: 'top_bihar_polity_panchayat',
    title: 'Bihar Panchayati Raj Act (2006): Pioneer in 50% Women Reservation',
    summary: 'The landmark legislation establishing 50% affirmative action for women and 20% for Extremely Backward Classes (EBC) in grassroot democracy.',
    explanation: 'Enacted in 2006 under the Nitish Kumar government, making Bihar the very first state in the country to provide 50% reservation for women in all tiers of Panchayati Raj Institutions (Gram Panchayat, Panchayat Samiti, and Zilla Parishad) as well as Mukhia/Pramukh/Adhyaksha posts. Also provided 20% reservation for EBCs and proportional reservation for SC/STs. Empowered Gram Kachhari with judicial powers for petty civil and criminal disputes headed by a Sarpanch.',
    examples: ['Over 50% elected village heads across Bihar are women, boosting female socio-political empowerment', 'Gram Sabha mandatory 4 meetings a year'],
    keyPoints: [
      'Panchayat tenure is 5 years; elections conducted by the Bihar State Election Commission (SEC).',
      'Gram Panchayat is established for a population of approximately 7,000.',
      'Panchayat Samiti is formed at the Block level (1 representative per 5,000 population).',
      'Zilla Parishad operates at District level (1 representative per 50,000 population).',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: ['c_panchayati_raj_73'],
    relatedIds: ['c_panchayati_raj_73', 'c_bihar_economy_saat_nischay'],
    tags: ['Bihar Special', 'BPSC', 'Polity', 'Panchayati Raj', 'Women Reservation', 'GS-2'],
  },
  {
    id: 'c_patna_kalam',
    subjectId: 'sub_bihar',
    topicId: 'top_bihar_art_culture',
    title: 'Patna Kalam Painting & Folk Arts of Bihar (Madhubani & Manjusha)',
    summary: 'The distinguished Mughal-British fusion miniature school of painting in Bihar and traditional indigenous folk artistic traditions.',
    explanation: 'Patna Kalam (Company School of Painting) flourished in the 18th-19th centuries in Patna (Lodi Katra, Mughal Toli, Dewan Mohalla) after artists migrated from Murshidabad. Key features: miniature format, painted directly with brush without pencil sketches (Kajli Syahi technique), focus on common life of ordinary people (blacksmiths, washermen, palanquin bearers, bird catchers), use of natural colours from minerals/flowers, and bird/squirrel hair brushes. Famous painters: Sewak Ram, Hulas Lal, Shiv Lal, and Ishwari Prasad Verma. Madhubani / Mithila Painting (Bharni, Katchni, Tantrik, Godna, Kohbar styles) and Manjusha Art (Angika region snake art on jute/paper) represent vibrant living traditions.',
    examples: ['Patna Kalam painting "Lohar" (Blacksmith) and "Chidiya Maar" (Bird Catcher)', 'Madhubani painting GI tag and global recognition by Padma awardees like Ganga Devi, Mahasundari Devi, and Dulari Devi'],
    keyPoints: [
      'Patna Kalam was primarily a male-dominated commercial art patronized by local gentry and British officers.',
      'Madhubani painting was traditionally practiced by women on mud walls (Bhitti Chitra) and floors (Aripan) during rituals and weddings.',
      'Manjusha Art is based on the folklore of Bihula-Bishahari and is characterized by a three-colour palette (Pink, Green, Yellow).',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_mauryan_empire'],
    tags: ['Bihar Special', 'BPSC', 'Art and Culture', 'Patna Kalam', 'Madhubani', 'GS-1'],
  },

  // --- ETHICS (GS-IV) CONCEPTS ---
  {
    id: 'c_probity_governance',
    subjectId: 'sub_ethics',
    topicId: 'top_probity_governance',
    title: 'Probity in Governance, Citizen’s Charters & Nolan Committee Principles',
    summary: 'The standard of impeccable integrity, public trust, transparency, and accountability in administrative action and governance.',
    explanation: 'Probity in governance is an essential requirement for socio-economic development and corruption-free delivery of public services. Encompasses adherence to Nolan Committee’s Seven Principles of Public Life: Selflessness, Integrity, Objectivity, Accountability, Openness, Honesty, and Leadership. Implemented through structural tools: Right to Information (RTI Act 2005), Citizen’s Charters, Social Audits, Whistleblower Protection, e-Procurement, and Central Vigilance Commission (CVC) integrity pacts.',
    examples: ['Implementation of Sevottam Model for public grievance redressal', 'Mandatory declaration of assets and liabilities by public servants'],
    keyPoints: [
      'Probity goes beyond mere financial honesty to include intellectual integrity, fairness, and avoiding conflict of interest.',
      'Citizen’s Charter is a voluntary written declaration by service providers about standards, choice, accessibility, and grievance redressal.',
      'Second Administrative Reforms Commission (2nd ARC) 4th Report dedicated to "Ethics in Governance".',
    ],
    difficulty: 'INTERMEDIATE',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_basic_structure'],
    tags: ['Ethics', 'GS-4', 'Governance', 'Probity', 'Nolan Principles'],
  },

  // --- CURRENT AFFAIRS CONCEPTS ---
  {
    id: 'c_ca_general',
    subjectId: 'sub_ca',
    topicId: 'top_national_governance',
    title: 'Contemporary Policy Architecture & Civil Services Syllabus Linkage',
    summary: 'The methodology of analyzing daily governmental policies, bilateral treaties, and scientific breakthroughs against the UPSC/BPSC syllabus.',
    explanation: 'Current affairs is the dynamic overlay of the core static civil services syllabus. Every news event must be traced back to its constitutional (GS-2), macroeconomic (GS-3), environmental (GS-3), ethical (GS-4), or state-specific (Bihar Special) foundation.',
    examples: ['Bharatiya Nyaya Sanhita (BNS) replacement of IPC linked to Criminal Justice Reforms (GS-2)', 'Digital Personal Data Protection Act 2023 linked to Article 21 Privacy (GS-2)'],
    keyPoints: [
      'Always focus on official Government sources (PIB, India.gov.in, Gazette notifications, Supreme Court orders).',
      'Distinguish between Prelims objective factual components and Mains multi-dimensional analytical dimensions.',
      'Incorporate state-specific policy rollouts (e.g. Bihar Saat Nischay-2 and Caste Survey welfare schemes) for BPSC CCE.',
    ],
    difficulty: 'BEGINNER',
    importance: 'HIGH',
    prerequisiteIds: [],
    relatedIds: ['c_art21', 'c_fiscal_fed', 'c_bihar_economy_saat_nischay'],
    tags: ['Current Affairs', 'Syllabus', 'PIB', 'UPSC', 'BPSC'],
  },
];
