import { OfficialPyqPaper } from './types.js';
import { UPSC_2026_GS1_QUESTIONS } from './upsc_2026_gs1.js';
import { UPSC_2026_CSAT_QUESTIONS } from './upsc_2026_csat.js';
import { UPSC_2025_GS1_QUESTIONS } from './upsc_2025_gs1.js';
import { UPSC_2025_CSAT_QUESTIONS } from './upsc_2025_csat.js';
import { UPSC_2024_GS1_QUESTIONS } from './upsc_2024_gs1.js';
import { UPSC_2024_CSAT_QUESTIONS } from './upsc_2024_csat.js';
import { UPSC_2023_GS1_QUESTIONS } from './upsc_2023_gs1.js';
import { UPSC_2023_CSAT_QUESTIONS } from './upsc_2023_csat.js';
import { UPSC_2022_GS1_QUESTIONS } from './upsc_2022_gs1.js';
import { UPSC_2022_CSAT_QUESTIONS } from './upsc_2022_csat.js';
import { UPSC_2021_GS1_QUESTIONS } from './upsc_2021_gs1.js';
import { UPSC_2021_CSAT_QUESTIONS } from './upsc_2021_csat.js';
import { UPSC_2020_GS1_QUESTIONS } from './upsc_2020_gs1.js';
import { UPSC_2020_CSAT_QUESTIONS } from './upsc_2020_csat.js';
import { BPSC_71ST_GS_QUESTIONS } from './bpsc_71st_gs.js';
import { BPSC_70TH_GS_QUESTIONS } from './bpsc_70th_gs.js';
import { BPSC_69TH_GS_QUESTIONS } from './bpsc_69th_gs.js';
import { BPSC_68TH_GS_QUESTIONS } from './bpsc_68th_gs.js';
import { BPSC_67TH_GS_QUESTIONS } from './bpsc_67th_gs.js';
import { BPSC_66TH_GS_QUESTIONS } from './bpsc_66th_gs.js';

export const OFFICIAL_PYQ_PAPERS: OfficialPyqPaper[] = [
  {
    id: 'paper_upsc_2026_gs1',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2026,
    examCycle: '2026',
    stage: 'Prelims',
    paper: 'GS Paper I',
    paperName: 'Civil Services (Preliminary) 2026 - General Studies Paper I',
    paperCode: 'CSP-GS1',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-26-GENERAL-STUDIES-PAPER-I.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 100,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'ANSWER_KEY_PENDING',
    language: 'bilingual',
    marksPerCorrect: 2,
    negativeMarking: 0.666,
    durationMinutes: 120,
    questions: UPSC_2026_GS1_QUESTIONS,
  },
  {
    id: 'paper_upsc_2026_csat',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2026,
    examCycle: '2026',
    stage: 'Prelims',
    paper: 'CSAT',
    paperName: 'Civil Services (Preliminary) 2026 - General Studies Paper II (CSAT)',
    paperCode: 'CSP-CSAT',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-26-GENERAL-STUDIES-PAPER-II.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 80,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'ANSWER_KEY_PENDING',
    language: 'bilingual',
    marksPerCorrect: 2.5,
    negativeMarking: 0.833,
    durationMinutes: 120,
    questions: UPSC_2026_CSAT_QUESTIONS,
  },
  {
    id: 'paper_upsc_2025_gs1',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2025,
    examCycle: '2025',
    stage: 'Prelims',
    paper: 'GS Paper I',
    paperName: 'Civil Services (Preliminary) 2025 - General Studies Paper I',
    paperCode: 'CSP-GS1',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-25-GENERAL-STUDIES-PAPER-I.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 100,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'ANSWER_KEY_PENDING',
    language: 'bilingual',
    marksPerCorrect: 2,
    negativeMarking: 0.666,
    durationMinutes: 120,
    questions: UPSC_2025_GS1_QUESTIONS,
  },
  {
    id: 'paper_upsc_2025_csat',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2025,
    examCycle: '2025',
    stage: 'Prelims',
    paper: 'CSAT',
    paperName: 'Civil Services (Preliminary) 2025 - General Studies Paper II (CSAT)',
    paperCode: 'CSP-CSAT',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-25-GENERAL-STUDIES-PAPER-II.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 80,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'ANSWER_KEY_PENDING',
    language: 'bilingual',
    marksPerCorrect: 2.5,
    negativeMarking: 0.833,
    durationMinutes: 120,
    questions: UPSC_2025_CSAT_QUESTIONS,
  },
  {
    id: 'paper_upsc_2024_gs1',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2024,
    examCycle: '2024',
    stage: 'Prelims',
    paper: 'GS Paper I',
    paperName: 'Civil Services (Preliminary) 2024 - General Studies Paper I',
    paperCode: 'CSP-GS1',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-24-GENERAL-STUDIES-PAPER-I-180624.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 100,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2,
    negativeMarking: 0.666,
    durationMinutes: 120,
    questions: UPSC_2024_GS1_QUESTIONS,
  },
  {
    id: 'paper_upsc_2024_csat',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2024,
    examCycle: '2024',
    stage: 'Prelims',
    paper: 'CSAT',
    paperName: 'Civil Services (Preliminary) 2024 - General Studies Paper II (CSAT)',
    paperCode: 'CSP-CSAT',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-24-GENERAL-STUDIES-PAPER-II-180624.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 80,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2.5,
    negativeMarking: 0.833,
    durationMinutes: 120,
    questions: UPSC_2024_CSAT_QUESTIONS,
  },
  {
    id: 'paper_upsc_2023_gs1',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2023,
    examCycle: '2023',
    stage: 'Prelims',
    paper: 'GS Paper I',
    paperName: 'Civil Services (Preliminary) 2023 - General Studies Paper I',
    paperCode: 'CSP-GS1',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-23-GeneralStudiesPaper-I-290523.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 100,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2,
    negativeMarking: 0.666,
    durationMinutes: 120,
    questions: UPSC_2023_GS1_QUESTIONS,
  },
  {
    id: 'paper_upsc_2023_csat',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2023,
    examCycle: '2023',
    stage: 'Prelims',
    paper: 'CSAT',
    paperName: 'Civil Services (Preliminary) 2023 - General Studies Paper II (CSAT)',
    paperCode: 'CSP-CSAT',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-23-GeneralStudiesPaper-II-290523.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 80,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2.5,
    negativeMarking: 0.833,
    durationMinutes: 120,
    questions: UPSC_2023_CSAT_QUESTIONS,
  },
  {
    id: 'paper_upsc_2022_gs1',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2022,
    examCycle: '2022',
    stage: 'Prelims',
    paper: 'GS Paper I',
    paperName: 'Civil Services (Preliminary) 2022 - General Studies Paper I',
    paperCode: 'CSP-GS1',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-22-GS-P-I-060622.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 100,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2,
    negativeMarking: 0.666,
    durationMinutes: 120,
    questions: UPSC_2022_GS1_QUESTIONS,
  },
  {
    id: 'paper_upsc_2022_csat',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2022,
    examCycle: '2022',
    stage: 'Prelims',
    paper: 'CSAT',
    paperName: 'Civil Services (Preliminary) 2022 - General Studies Paper II (CSAT)',
    paperCode: 'CSP-CSAT',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-22-GS-P-II-060622.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 80,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2.5,
    negativeMarking: 0.833,
    durationMinutes: 120,
    questions: UPSC_2022_CSAT_QUESTIONS,
  },
  {
    id: 'paper_upsc_2021_gs1',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2021,
    examCycle: '2021',
    stage: 'Prelims',
    paper: 'GS Paper I',
    paperName: 'Civil Services (Preliminary) 2021 - General Studies Paper I',
    paperCode: 'CSP-GS1',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/CSP-2021-GS-P1.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 100,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2,
    negativeMarking: 0.666,
    durationMinutes: 120,
    questions: UPSC_2021_GS1_QUESTIONS,
  },
  {
    id: 'paper_upsc_2021_csat',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2021,
    examCycle: '2021',
    stage: 'Prelims',
    paper: 'CSAT',
    paperName: 'Civil Services (Preliminary) 2021 - General Studies Paper II (CSAT)',
    paperCode: 'CSP-CSAT',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/CSP-2021-GS-P2.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 80,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2.5,
    negativeMarking: 0.833,
    durationMinutes: 120,
    questions: UPSC_2021_CSAT_QUESTIONS,
  },
  {
    id: 'paper_upsc_2020_gs1',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2020,
    examCycle: '2020',
    stage: 'Prelims',
    paper: 'GS Paper I',
    paperName: 'Civil Services (Preliminary) 2020 - General Studies Paper I',
    paperCode: 'CSP-GS1',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-20-GS-P-I.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 100,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2,
    negativeMarking: 0.666,
    durationMinutes: 120,
    questions: UPSC_2020_GS1_QUESTIONS,
  },
  {
    id: 'paper_upsc_2020_csat',
    exam: 'UPSC CSE',
    examName: 'Civil Services (Preliminary) Examination',
    year: 2020,
    examCycle: '2020',
    stage: 'Prelims',
    paper: 'CSAT',
    paperName: 'Civil Services (Preliminary) 2020 - General Studies Paper II (CSAT)',
    paperCode: 'CSP-CSAT',
    officialSourceUrl: 'https://www.upsc.gov.in/examinations/previous-question-papers',
    officialPaperUrl: 'https://www.upsc.gov.in/sites/default/files/QP-CSP-20-GS-P-II.pdf',
    sourceDomain: 'upsc.gov.in',
    expectedQuestionCount: 80,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 2.5,
    negativeMarking: 0.833,
    durationMinutes: 120,
    questions: UPSC_2020_CSAT_QUESTIONS,
  },
  {
    id: 'paper_bpsc_71st_gs',
    exam: 'BPSC',
    examName: 'Combined Competitive Examination (CCE)',
    year: 2025,
    examCycle: '71st CCE',
    stage: 'Prelims',
    paper: 'General Studies',
    paperName: '71st BPSC Combined Competitive (Preliminary) Examination - General Studies',
    paperCode: 'BPSC-CCE-71',
    officialSourceUrl: 'https://bpsc.bihar.gov.in/question-booklets/',
    officialPaperUrl: 'https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/QuestionBooklets/General-Studies-4.pdf',
    sourceDomain: 'bpsc.bihar.gov.in',
    expectedQuestionCount: 150,
    verificationStatus: 'OFFICIAL_VERIFIED',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 1,
    negativeMarking: 0.333,
    durationMinutes: 120,
    questions: BPSC_71ST_GS_QUESTIONS,
  },
  {
    id: 'paper_bpsc_70th_gs',
    exam: 'BPSC',
    examName: 'Combined Competitive Examination (CCE)',
    year: 2024,
    examCycle: '70th CCE',
    stage: 'Prelims',
    paper: 'General Studies',
    paperName: '70th BPSC Combined Competitive (Preliminary) Examination - General Studies',
    paperCode: 'BPSC-CCE-70',
    officialSourceUrl: 'https://bpsc.bihar.gov.in/question-booklets/',
    officialPaperUrl: 'https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/QuestionBooklets/General-Studies-1.pdf',
    sourceDomain: 'bpsc.bihar.gov.in',
    expectedQuestionCount: 150,
    verificationStatus: 'INCOMPLETE',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 1,
    negativeMarking: 0.333,
    durationMinutes: 120,
    questions: BPSC_70TH_GS_QUESTIONS,
  },
  {
    id: 'paper_bpsc_69th_gs',
    exam: 'BPSC',
    examName: 'Combined Competitive Examination (CCE)',
    year: 2023,
    examCycle: '69th CCE',
    stage: 'Prelims',
    paper: 'General Studies',
    paperName: '69th BPSC Combined Competitive (Preliminary) Examination - General Studies',
    paperCode: 'BPSC-CCE-69',
    officialSourceUrl: 'https://bpsc.bihar.gov.in/question-booklets/',
    officialPaperUrl: 'https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/QuestionBooklets/General-Studies.pdf',
    sourceDomain: 'bpsc.bihar.gov.in',
    expectedQuestionCount: 150,
    verificationStatus: 'INCOMPLETE',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 1,
    negativeMarking: 0.333,
    durationMinutes: 120,
    questions: BPSC_69TH_GS_QUESTIONS,
  },
  {
    id: 'paper_bpsc_68th_gs',
    exam: 'BPSC',
    examName: 'Combined Competitive Examination (CCE)',
    year: 2023,
    examCycle: '68th CCE',
    stage: 'Prelims',
    paper: 'General Studies',
    paperName: '68th BPSC Combined Competitive (Preliminary) Examination - General Studies',
    paperCode: 'BPSC-CCE-68',
    officialSourceUrl: 'https://bpsc.bihar.gov.in/question-booklets/',
    officialPaperUrl: 'https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/QuestionBooklets/General-Studies-2.pdf',
    sourceDomain: 'bpsc.bihar.gov.in',
    expectedQuestionCount: 150,
    verificationStatus: 'INCOMPLETE',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 1,
    negativeMarking: 0.25,
    durationMinutes: 120,
    questions: BPSC_68TH_GS_QUESTIONS,
  },
  {
    id: 'paper_bpsc_67th_gs',
    exam: 'BPSC',
    examName: 'Combined Competitive Examination (CCE)',
    year: 2022,
    examCycle: '67th CCE',
    stage: 'Prelims',
    paper: 'General Studies',
    paperName: '67th BPSC Combined Competitive (Preliminary) Examination - General Studies',
    paperCode: 'BPSC-CCE-67',
    officialSourceUrl: 'https://bpsc.bihar.gov.in/question-booklets/',
    officialPaperUrl: 'https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/QuestionBooklets/General-Studies-3.pdf',
    sourceDomain: 'bpsc.bihar.gov.in',
    expectedQuestionCount: 150,
    verificationStatus: 'INCOMPLETE',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 1,
    negativeMarking: 0,
    durationMinutes: 120,
    questions: BPSC_67TH_GS_QUESTIONS,
  },
  {
    id: 'paper_bpsc_66th_gs',
    exam: 'BPSC',
    examName: 'Combined Competitive Examination (CCE)',
    year: 2020,
    examCycle: '66th CCE',
    stage: 'Prelims',
    paper: 'General Studies',
    paperName: '66th BPSC Combined Competitive (Preliminary) Examination - General Studies',
    paperCode: 'BPSC-CCE-66',
    officialSourceUrl: 'https://bpsc.bihar.gov.in/question-booklets/',
    officialPaperUrl: 'https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/QuestionBooklets/General-Studies-6.pdf',
    sourceDomain: 'bpsc.bihar.gov.in',
    expectedQuestionCount: 150,
    verificationStatus: 'INCOMPLETE',
    answerKeyStatus: 'OFFICIAL_KEY_VERIFIED',
    language: 'bilingual',
    marksPerCorrect: 1,
    negativeMarking: 0,
    durationMinutes: 120,
    questions: BPSC_66TH_GS_QUESTIONS,
  },
];
